### ISSUE TITLE
Categories?

### ISSUE THREAD

**Issue by JC123** [kytulendu/Gw2Browser#1]
I am just curious about the Pack File categorization. Specifically why mapc is categorized as "Map Parameter" and cntc as "Map Content"

**Comment by kytulendu** [comment]
As I check the chunk type from gw2formats, "mapc" should be categorize as "Map" and "cntc" as "Content" or something.
I think it some kind of programmer error here :P

**Comment by JC123** [comment]
Yeah, figured it was just an oversight. Cntc is a tree like hierarchy of _all_ the game content. I see mapc rendering on the todo list. You may be interested in checking out how [Tyria3d](http://www.tyria3d.com) renders them.
